#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# infra/quickstart.sh — interactive deployment script
# ───────────────────────────────────────────────────────────────────
# Run on a fresh Hetzner Ubuntu/Debian server after git-clone:
#   cd ai-command-center/infra
#   sudo bash quickstart.sh
#
# Does:
#   · checks/installs Docker if missing
#   · interactively builds .env (prompts for secrets, auto-gens passwords)
#   · opens UFW ports 80/443
#   · verifies DNS A-record points here
#   · docker compose up -d --build
#   · waits for /api/health
#   · sets Telegram webhook if voice-bot token present
#   · prints final status with all relevant URLs
# ═══════════════════════════════════════════════════════════════════

set -euo pipefail

BLUE='\033[34m'
GREEN='\033[32m'
RED='\033[31m'
YELLOW='\033[33m'
RESET='\033[0m'

say()  { echo -e "${BLUE}→${RESET} $*"; }
ok()   { echo -e "${GREEN}✓${RESET} $*"; }
warn() { echo -e "${YELLOW}⚠${RESET} $*"; }
die()  { echo -e "${RED}❌${RESET} $*" >&2; exit 1; }

# ── Sanity checks ──
[[ -f docker-compose.yml ]] || die "Запускай из infra/: cd ai-command-center/infra"
[[ -f Caddyfile ]] || die "Caddyfile не найден"
[[ -f .env.example ]] || die ".env.example не найден"

# Detect sudo necessity
SUDO=""
if [[ $EUID -ne 0 ]]; then
  if command -v sudo &>/dev/null; then
    SUDO="sudo"
  else
    die "Нужен root или sudo"
  fi
fi

# ── Step 1: Docker ──
if ! command -v docker &>/dev/null; then
  say "Устанавливаю Docker"
  $SUDO apt-get update -qq
  $SUDO apt-get install -y -qq curl ca-certificates dnsutils openssl
  curl -fsSL https://get.docker.com | $SUDO sh
  $SUDO usermod -aG docker "$USER" 2>/dev/null || true
  ok "Docker установлен"
else
  ok "Docker уже есть ($(docker --version | awk '{print $3}' | tr -d ','))"
fi

if ! docker compose version &>/dev/null; then
  say "Docker compose plugin..."
  $SUDO apt-get install -y -qq docker-compose-plugin || true
fi

# ── Step 2: .env ──
ENV_PATH="$(pwd)/.env"
SKIP_PROMPTS=0
if [[ -f "$ENV_PATH" ]]; then
  echo
  read -rp "$ENV_PATH уже существует. Перезаписать? [y/N] " ans
  if [[ ! "$ans" =~ ^[Yy]$ ]]; then
    SKIP_PROMPTS=1
    ok "Использую существующий .env"
  fi
fi

if [[ $SKIP_PROMPTS -eq 0 ]]; then
  echo
  echo "═══════════════════════════════════════════════════════════════"
  echo "  Настройка .env (всё можно потом отредактировать вручную)"
  echo "═══════════════════════════════════════════════════════════════"
  echo

  read -rp "Домен (например ai-growth-office.ru): " DOMAIN
  [[ -n "$DOMAIN" ]] || die "Домен обязателен"

  read -rp "Email для Let's Encrypt [admin@$DOMAIN]: " ACME_EMAIL
  ACME_EMAIL="${ACME_EMAIL:-admin@$DOMAIN}"

  echo
  echo "── API-ключи (Enter если ещё нет — пропишешь позже в .env) ──"
  read -rp "ANTHROPIC_API_KEY:       " ANTHROPIC_KEY
  read -rp "ELEVENLABS_API_KEY:      " ELEVEN_KEY
  read -rp "DEEPGRAM_API_KEY:        " DEEPGRAM_KEY

  echo
  echo "── Telegram (Enter если ещё нет) ──"
  read -rp "TG_BOT_TOKEN (notify-bot):    " TG_BOT_TOKEN_IN
  read -rp "TG_CHAT_ID (твой user_id):    " TG_CHAT_ID_IN
  read -rp "TG_VOICE_BOT_TOKEN (Phase 5): " TG_VOICE_TOKEN

  PG_PASS=$(openssl rand -hex 24)
  TG_SECRET=$(openssl rand -hex 24)

  cat > "$ENV_PATH" <<EOF
# Generated by quickstart.sh on $(date -Iseconds)
PUBLIC_HOST=$DOMAIN
PUBLIC_BASE_URL=https://$DOMAIN
ACME_EMAIL=$ACME_EMAIL

POSTGRES_DB=aio
POSTGRES_USER=aio
POSTGRES_PASSWORD=$PG_PASS

ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
ELEVENLABS_API_KEY=${ELEVEN_KEY}
DEEPGRAM_API_KEY=${DEEPGRAM_KEY}

TG_BOT_TOKEN=${TG_BOT_TOKEN_IN}
TG_CHAT_ID=${TG_CHAT_ID_IN}
TG_VOICE_BOT_TOKEN=${TG_VOICE_TOKEN}
TG_WEBHOOK_SECRET=$TG_SECRET

YTDLP_SERVICE_URL=
YTDLP_SERVICE_API_KEY=
EOF
  chmod 600 "$ENV_PATH"
  ok ".env создан (chmod 600). Пароли БД и webhook-secret сгенерированы автоматически."
fi

# Load env
set -a
# shellcheck disable=SC1090
source "$ENV_PATH"
set +a

# ── Step 3: Firewall ──
if command -v ufw &>/dev/null; then
  say "Настройка UFW"
  $SUDO ufw allow OpenSSH >/dev/null 2>&1 || true
  $SUDO ufw allow 80,443/tcp >/dev/null 2>&1 || true
  $SUDO ufw allow 443/udp >/dev/null 2>&1 || true
  yes | $SUDO ufw --force enable >/dev/null 2>&1 || true
  ok "UFW: 22, 80, 443 открыты"
fi

# ── Step 4: DNS check ──
say "Проверка DNS"
SERVER_IP=$(curl -s4 https://ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
DNS_IP=$(dig +short "$PUBLIC_HOST" A | head -1 || true)
if [[ -z "$DNS_IP" ]]; then
  warn "$PUBLIC_HOST ещё не резолвится. Caddy не получит TLS-сертификат."
elif [[ "$DNS_IP" != "$SERVER_IP" ]]; then
  warn "$PUBLIC_HOST → $DNS_IP, но сервер — $SERVER_IP"
  warn "Дождись пока DNS обновится (5-30 мин обычно)"
else
  ok "DNS: $PUBLIC_HOST → $SERVER_IP ✓"
fi

# Confirm before lift-off
echo
read -rp "Поднимаем стек (docker compose up -d --build)? [Y/n] " go
if [[ "$go" =~ ^[Nn]$ ]]; then
  warn "Прерывание — запусти 'docker compose up -d --build' вручную когда готов"
  exit 0
fi

# ── Step 5: Bring up the stack ──
say "Сборка и запуск контейнеров (3-5 минут на первый build)"
$SUDO docker compose up -d --build

# ── Step 6: Wait for health ──
say "Жду health-check"
HEALTHY=0
for i in $(seq 1 60); do
  if curl -fsk "https://localhost/api/health" 2>/dev/null | grep -q '"ok":true'; then
    HEALTHY=1
    break
  fi
  if [[ $((i % 10)) -eq 0 ]]; then
    echo "  ... ${i}s"
  fi
  sleep 2
done

echo
if [[ $HEALTHY -eq 1 ]]; then
  ok "Сервис отвечает на /api/health"
else
  warn "Health-check не прошёл за 2 минуты — смотри логи: docker compose logs"
fi

# ── Step 7: Telegram webhook ──
if [[ -n "${TG_VOICE_BOT_TOKEN:-}" ]] && [[ "$TG_VOICE_BOT_TOKEN" != "" ]]; then
  say "Установка Telegram webhook для voice-бота"
  WEBHOOK_RES=$(curl -s -X POST "https://api.telegram.org/bot${TG_VOICE_BOT_TOKEN}/setWebhook" \
    --data-urlencode "url=${PUBLIC_BASE_URL}/api/tg-voice-webhook" \
    --data-urlencode "secret_token=${TG_WEBHOOK_SECRET}" \
    --data-urlencode 'allowed_updates=["message","callback_query"]')
  echo "  $WEBHOOK_RES"
fi

# ── Final status ──
echo
echo "═══════════════════════════════════════════════════════════════"
echo "  Финальный статус"
echo "═══════════════════════════════════════════════════════════════"
$SUDO docker compose ps

echo
echo "── Полезные URL ──"
echo "  • Главная:        https://$PUBLIC_HOST/"
echo "  • Транскрибер:    https://$PUBLIC_HOST/transcribe"
echo "  • Persona-train:  https://$PUBLIC_HOST/persona-train"
echo "  • Health:         https://$PUBLIC_HOST/api/health"

echo
echo "── Команды для дальнейшей работы ──"
echo "  Логи всех сервисов:   docker compose logs -f"
echo "  Логи Caddy (TLS):     docker compose logs caddy --tail=50"
echo "  Перезапуск backend:   docker compose restart ai-office"
echo "  Бэкап БД:             docker compose exec postgres pg_dump -U aio aio > backup.sql"
echo "  Обновление кода:      git pull && docker compose up -d --build"
echo
ok "Готово."
