// 20 ниш соцсетей × 10 prompt-паков на каждую.
// Используется на /generate как альтернатива дефолтным AVATAR_STYLES.
// Формат promptStyle — короткое описание ИЗМЕНЯЕМОГО (wardrobe + setting + lighting),
// которое идёт после "NEW SETTING:" в edit-mode шаблоне (см. buildAvatarPrompt).

export type NichePrompt = {
  slug: string;       // уникален в рамках ниши: 'beauty-skincare-01'
  label: string;      // 'Glass Skin Editorial'
  description: string;// короткий ru-сабтайтл для UI
  promptStyle: string;
  allowRigidPose?: boolean;
};

export type Niche = {
  slug: string;
  label: string;
  description: string;
  prompts: NichePrompt[];
};

const N = (
  base: string,
  items: Array<Omit<NichePrompt, 'slug'> & { id: string }>,
): NichePrompt[] => items.map((it) => ({ slug: `${base}-${it.id}`, ...it }));

export const NICHES: Niche[] = [
  {
    slug: 'beauty-skincare',
    label: 'Beauty & Skincare',
    description: 'Уход за кожей, макияж, бьюти-контент.',
    prompts: N('beauty-skincare', [
      { id: '01', label: 'Glass Skin Editorial', description: 'Глянцевая кожа, мягкий beauty-свет.',
        promptStyle: 'wearing a clean ivory silk slip top, in a minimal off-white beauty studio, soft diffused ringlight beauty lighting, dewy glass-skin makeup look, magazine beauty editorial composition.', allowRigidPose: true },
      { id: '02', label: 'Sephora Counter', description: 'Бьюти-ритейл, подсветка витрины.',
        promptStyle: 'wearing a chic black blazer over white tee, standing at a high-end cosmetics retail counter, warm spotlights on lipstick displays behind, glossy black surfaces with subtle pink reflections, polished retail aesthetic.' },
      { id: '03', label: 'Spa Glow Retreat', description: 'Спа, тёплый янтарь, мрамор.',
        promptStyle: 'wearing a soft white spa robe, in a luxury marble spa room, warm amber candle glow, eucalyptus accents, calm wellness aesthetic, shallow depth of field.' },
      { id: '04', label: 'Hollywood Vanity', description: 'Гримёрка с круглыми лампами.',
        promptStyle: 'wearing a satin blush dressing-room robe, seated at a Hollywood vanity mirror framed by warm tungsten bulbs, soft golden flattering glow, dressing-room luxury mood.' },
      { id: '05', label: 'Korean Skincare Lab', description: 'Пастель, аэстетик k-beauty.',
        promptStyle: 'wearing a pastel cardigan over white tee, in a pastel-pink minimal k-beauty lab, soft uniform daylight, glossy product surfaces and sheet-mask aesthetic, cute clean composition.', allowRigidPose: true },
      { id: '06', label: 'Derma Clinic Pro', description: 'Белый халат, дерматолог.',
        promptStyle: 'wearing a crisp white dermatologist coat over neutral top, in a bright minimalist medical aesthetic clinic, soft cool clinical daylight, clean white surfaces, professional trustworthy composition.' },
      { id: '07', label: 'Ring-Light Influencer', description: 'Reels, ringlight, белая стена.',
        promptStyle: 'wearing a soft pastel knit, against a clean white wall, frontal ringlight catchlights in the eyes, casual creator-at-home composition, vlog-ready framing.', allowRigidPose: true },
      { id: '08', label: 'Sun-Kissed No-Makeup', description: 'Золотой час, естественность.',
        promptStyle: 'wearing a simple natural linen top, in a sun-drenched outdoor garden, golden-hour rim light, no-makeup makeup look, breezy effortless mood, shallow depth of field.' },
      { id: '09', label: 'Bath Self-Care', description: 'Свечи, шампанское, релакс.',
        promptStyle: 'wearing a plush white towel wrap (chest-up framing only), in a candlelit luxury bathroom with marble tub, warm flickering candle ambient light, soft mist, intimate wellness mood.' },
      { id: '10', label: 'Vogue Beauty Cover', description: 'Монохром, vogue beauty.',
        promptStyle: 'wearing a sleek black turtleneck, against a deep charcoal seamless backdrop, dramatic beauty key light, polished editorial makeup, Vogue beauty cover composition.', allowRigidPose: true },
    ]),
  },
  {
    slug: 'fitness-wellness',
    label: 'Fitness & Wellness',
    description: 'Тренировки, ЗОЖ, биохакинг.',
    prompts: N('fitness-wellness', [
      { id: '01', label: 'Premium Gym Floor', description: 'Зеркальный зал, тёмный фон.',
        promptStyle: 'wearing matte-black premium athletic gear, on a dark high-end gym floor with mirrors and rubber matting, dramatic side spotlights, athletic confident mood, gym-magazine cover composition.' },
      { id: '02', label: 'Sunrise Yoga Deck', description: 'Утро, океан, йога.',
        promptStyle: 'wearing minimal beige yoga set, on a wooden deck overlooking the ocean at sunrise, warm coral light, calm focused expression, wellness lifestyle aesthetic.' },
      { id: '03', label: 'Crossfit Box', description: 'Тяжёлый кроссфит, индустриальный лофт.',
        promptStyle: 'wearing a sweat-toned grey tee and shorts, in a raw concrete crossfit box with barbells in soft background blur, harsh overhead industrial light, gritty fitness mood.' },
      { id: '04', label: 'Running Track Editorial', description: 'Стадион, спринт-эстетика.',
        promptStyle: 'wearing sleek modern running gear, on a red running track at golden hour, low-angle dynamic stance, motion-blurred stadium background, sport editorial composition.' },
      { id: '05', label: 'Biohacker Lab', description: 'Чистый минимал, биохакинг.',
        promptStyle: 'wearing minimal modern athletic-casual outfit (zip top over tee), in a futurist biohacker lab with soft white surfaces and subtle teal accents, clinical-modern lighting, focused intellectual mood.' },
      { id: '06', label: 'Pilates Studio', description: 'Пилатес, нежный пастельный свет.',
        promptStyle: 'wearing a chic pastel pilates set, in a minimalist pilates studio with reformer equipment in blurred background, soft warm window daylight, graceful refined mood.', allowRigidPose: true },
      { id: '07', label: 'Forest Trail Run', description: 'Лесная пробежка, плед утренний свет.',
        promptStyle: 'wearing technical trail running gear, on a forest trail in cool morning mist, soft diffused green-tinted daylight filtering through trees, energetic outdoor mood.' },
      { id: '08', label: 'Boxing Ring Mood', description: 'Бокс, контровик, ринг.',
        promptStyle: 'wearing a sleeveless boxing top with hand wraps visible, in a dim boxing gym with a single hard spotlight, ring ropes blurred behind, dramatic high-contrast shadow play.' },
      { id: '09', label: 'Cold Plunge Wellness', description: 'Айсбат, биохакинг, дерево.',
        promptStyle: 'wearing a black athletic recovery hoodie, next to a wooden cold-plunge tub in a sauna lounge, warm cedar tones, steamy ambient backlight, recovery-ritual mood.' },
      { id: '10', label: 'Smoothie Kitchen Reels', description: 'Кухня, чистый завтрак.',
        promptStyle: 'wearing a soft cream activewear set, in a bright modern kitchen with fresh produce and a green smoothie on the counter, clean morning daylight, healthy lifestyle Reels composition.' },
    ]),
  },
  {
    slug: 'fashion-style',
    label: 'Fashion & Style',
    description: 'Мода, лукбуки, streetwear.',
    prompts: N('fashion-style', [
      { id: '01', label: 'Paris Street Style', description: 'Парижские улицы, осенний свет.',
        promptStyle: 'wearing a tailored beige trench over knit and slim trousers, on a parisian cobblestone street with haussmann facades blurred behind, soft overcast autumn daylight, fashion-week street-style composition.' },
      { id: '02', label: 'High Fashion Editorial', description: 'Vogue, монохром, драматика.',
        promptStyle: 'wearing a sculptural black designer outfit, in a stark seamless white studio, dramatic single key light with deep shadows, confident editorial pose, Vogue spread composition.', allowRigidPose: true },
      { id: '03', label: 'Streetwear Tokyo', description: 'Tokyo neon streetwear.',
        promptStyle: 'wearing oversized tech-streetwear (cargo, hoodie, beanie), in a neon-lit tokyo alley with shop signs glowing pink and cyan, rainy reflections, cinematic street mood.' },
      { id: '04', label: 'Old Money Riviera', description: 'Старые деньги, ривьера.',
        promptStyle: 'wearing a cream linen suit and silk scarf, on a sun-drenched mediterranean terrace, warm golden afternoon light, palm shadows, old-money riviera aesthetic.' },
      { id: '05', label: 'Y2K Pop Editorial', description: 'Y2K глянец, поп-эстетика.',
        promptStyle: 'wearing playful y2k-inspired outfit (denim and metallic accents), against a glossy magenta and chrome backdrop, bright pop studio lighting, glossy fashion-tabloid composition.' },
      { id: '06', label: 'Lookbook Mono', description: 'Лукбук, чистый минимал.',
        promptStyle: 'wearing a structured monochrome outfit in a single neutral tone, against a seamless studio cyclorama matching the wardrobe, even soft fashion-catalog lighting, lookbook composition.', allowRigidPose: true },
      { id: '07', label: 'Milan Atelier', description: 'Милан, мастерская кутюрье.',
        promptStyle: 'wearing impeccable italian tailoring, inside a luxury milan atelier with marble floors and gilded mirrors, warm directional window light, refined craftsmanship mood.' },
      { id: '08', label: 'Backstage Runway', description: 'Бэкстейдж, готовится модель.',
        promptStyle: 'wearing avant-garde runway-ready outfit, in a chaotic but glamorous backstage area with garment racks blurred behind, mixed tungsten makeup lighting, candid backstage moment.' },
      { id: '09', label: 'Vintage Denim Field', description: 'Деним, ретро поле, плёнка.',
        promptStyle: 'wearing vintage worn-in denim and a white tee, in a golden wheat field at sunset, warm 35mm film-grain look, americana fashion editorial mood.' },
      { id: '10', label: 'Neo-Minimal Tokyo Loft', description: 'Бруталист-лофт, neo-minimal.',
        promptStyle: 'wearing a long-line minimalist coat over wide trousers, in a brutalist concrete loft with floor-to-ceiling windows, cool grey daylight, architectural fashion mood.' },
    ]),
  },
  {
    slug: 'tech-software',
    label: 'Tech & Software',
    description: 'IT, разработка, продуктовые истории.',
    prompts: N('tech-software', [
      { id: '01', label: 'Y-Combinator Demo Day', description: 'Demo-day, LED-фон, cyan.',
        promptStyle: 'wearing a modern dark zip hoodie or unstructured blazer over tee, on a tech demo-day stage with massive LED backdrop in cyan tones, sharp keynote spotlight, confident founder pose.' },
      { id: '02', label: 'Engineering War Room', description: 'Мониторы, dark mode.',
        promptStyle: 'wearing a charcoal tech tee, in a darkened engineering war room with multiple monitors glowing with code, blue and amber screen light on the face, focused engineer mood.' },
      { id: '03', label: 'Modern Coworking', description: 'Лофт-офис, тёплое дерево.',
        promptStyle: 'wearing a smart-casual neutral outfit, in a stylish modern coworking space with warm wood and plants, large windows behind with soft daylight, productive startup mood.' },
      { id: '04', label: 'Hackathon Loft', description: 'Хакатон, ночной кодинг.',
        promptStyle: 'wearing a startup hoodie, at a long table in a hackathon loft at night, glow of laptop screens, energy-drink cans blurred in background, intense problem-solving mood.' },
      { id: '05', label: 'Product Launch Keynote', description: 'Apple-style keynote.',
        promptStyle: 'wearing a clean dark merino sweater, on a minimal black keynote stage with a single large apple-style display behind, premium spotlight, product-launch keynote energy.' },
      { id: '06', label: 'Server Room Cinematic', description: 'Дата-центр, неон.',
        promptStyle: 'wearing a slim dark tech jacket, in a modern server room with rows of racks and blue-cyan LED indicators, cinematic neon glow, datacenter scale mood.' },
      { id: '07', label: 'Cozy Indie Hacker', description: 'Уютный кабинет, MacBook.',
        promptStyle: 'wearing a comfortable knit, at a wooden home-office desk with a macbook and a mug, warm string lights and plants in background, indie-hacker cozy mood.' },
      { id: '08', label: 'AI Vision Studio', description: 'AI-визионер, голограмма.',
        promptStyle: 'wearing a modern dark structured jacket, in a futurist AI studio with faint holographic UI overlays and soft lime-cyan glow, sci-fi atmospheric lighting, visionary mood.' },
      { id: '09', label: 'SaaS Founder Portrait', description: 'SaaS-фаундер, чистый офис.',
        promptStyle: 'wearing a refined dark casual blazer, in a clean modern saas office with subtle brand accent colors on the wall, soft directional daylight, founder-portrait composition.' },
      { id: '10', label: 'Pitch Deck Cover', description: 'Pitch deck hero.',
        promptStyle: 'wearing a sharp modern outfit, against a deep navy seamless backdrop with subtle gradient, premium spotlight, confident pitch-deck-cover composition with negative space for a headline.', allowRigidPose: true },
    ]),
  },
  {
    slug: 'finance-investing',
    label: 'Finance & Investing',
    description: 'Инвестиции, трейдинг, финграмотность.',
    prompts: N('finance-investing', [
      { id: '01', label: 'Trader Desk', description: 'Множество мониторов, графики.',
        promptStyle: 'wearing a crisp white shirt with rolled sleeves, at a multi-monitor trading desk with green and red candlestick charts glowing, dim room with screen reflections on face, focused trader mood.' },
      { id: '02', label: 'Wall Street Suit', description: 'Wall Street, лестница.',
        promptStyle: 'wearing an impeccable navy pinstripe suit, on the steps of a classical financial-district building, sharp morning sun, power-broker composition.' },
      { id: '03', label: 'Bloomberg Anchor', description: 'Финансовое ТВ, голубой свет.',
        promptStyle: 'wearing a tailored charcoal suit with crisp shirt, on a bloomberg-style finance news set with LED screens of tickers behind, cool blue studio light, business-anchor authority mood.' },
      { id: '04', label: 'Private Bank Office', description: 'Wealth manager, темное дерево.',
        promptStyle: 'wearing a premium navy suit with silk tie, in a dark wood private-banking office with leather armchair, warm tungsten lamp light, trustworthy advisor mood.' },
      { id: '05', label: 'Hedge Fund Penthouse', description: 'Манхэттенский пентхаус.',
        promptStyle: 'wearing a refined charcoal suit (no tie), in a manhattan penthouse office with floor-to-ceiling windows and city skyline blurred behind, cinematic dusk light, hedge-fund mood.' },
      { id: '06', label: 'Crypto Trader Cyber', description: 'Trader cyber, нео-неон.',
        promptStyle: 'wearing a sleek black tech jacket, in a modern dark setup with neon green crypto charts glowing on screens, cyber-trader cinematic mood.' },
      { id: '07', label: 'Financial Coach Whiteboard', description: 'Финкоуч, доска и графики.',
        promptStyle: 'wearing smart-casual blazer over open-collar shirt, in front of a glass whiteboard with handwritten financial formulas, bright clean daylight, approachable educator mood.', allowRigidPose: true },
      { id: '08', label: 'Real Estate Investor', description: 'Investor open-house.',
        promptStyle: 'wearing a refined business-casual outfit, standing in a luxury empty open-house living room with floor-to-ceiling windows, warm afternoon light, real-estate-investor composition.' },
      { id: '09', label: 'CNBC Studio Insert', description: 'CNBC-style studio set.',
        promptStyle: 'wearing a sharp business suit, on a glossy financial-news studio set with stock ticker LED ribbons in background, bright tv-studio lighting, commentator authority mood.', allowRigidPose: true },
      { id: '10', label: 'Wealth Lifestyle', description: 'Wealth lifestyle, supercar/cigar.',
        promptStyle: 'wearing a luxury dark suit, in a private members club lounge with leather chesterfields and amber whisky glass on table, warm chiaroscuro lighting, premium wealth mood.' },
    ]),
  },
  {
    slug: 'real-estate',
    label: 'Real Estate',
    description: 'Недвижимость, элитные показы.',
    prompts: N('real-estate', [
      { id: '01', label: 'Luxury Open House', description: 'Открытый показ, лофт.',
        promptStyle: 'wearing a tailored neutral suit, in a high-end open-house living room with marble floors and oversized windows, soft afternoon daylight, real-estate-pro composition.' },
      { id: '02', label: 'Manhattan Skyline', description: 'Pent-house, panorama.',
        promptStyle: 'wearing a refined charcoal suit, in a manhattan penthouse with skyline visible at dusk, warm interior lamps and cool blue exterior glow, luxury-broker mood.' },
      { id: '03', label: 'Suburban Family Home', description: 'Pretty suburban front porch.',
        promptStyle: 'wearing a friendly business-casual outfit, on the porch of a beautiful suburban family home with green lawn, golden-hour warm light, approachable agent mood.' },
      { id: '04', label: 'Modern Glass Villa', description: 'Modern glass villa pool.',
        promptStyle: 'wearing a relaxed premium business outfit, by the pool of a modern glass-and-concrete villa, midday clear-blue lighting, luxury-listing mood.' },
      { id: '05', label: 'Open House Sign', description: 'For Sale sign, smiling agent.',
        promptStyle: 'wearing a smart blazer over open shirt, next to a sleek "For Sale" sign in a manicured front yard, bright clean daylight, trustworthy local-agent composition.' },
      { id: '06', label: 'Empty Loft Listing', description: 'Loft, индустриал.',
        promptStyle: 'wearing a modern dark business outfit, in an empty industrial loft with exposed brick and big factory windows, soft directional daylight, listing-showcase mood.' },
      { id: '07', label: 'Beachfront Property', description: 'Океан, белый дом.',
        promptStyle: 'wearing a crisp white linen shirt, on the wooden deck of a beachfront luxury property with ocean horizon behind, warm coastal afternoon light, premium beachfront mood.' },
      { id: '08', label: 'Architect Plans', description: 'Чертежи, новостройка.',
        promptStyle: 'wearing a smart-casual blazer, reviewing architectural drawings on a glass table in a sunlit modern construction-office, cool clean daylight, developer-pro mood.' },
      { id: '09', label: 'Marble Staircase', description: 'Marble grand staircase.',
        promptStyle: 'wearing a refined neutral suit, at the base of a sweeping marble staircase in a luxury home foyer, warm chandelier light, premium-listing composition.' },
      { id: '10', label: 'Investor Property Tour', description: 'Stripped property tour.',
        promptStyle: 'wearing a relaxed business-casual outfit (rolled sleeves, no tie), inside a property mid-renovation with raw walls and tools, dramatic side daylight, hands-on-investor mood.' },
    ]),
  },
  {
    slug: 'food-cooking',
    label: 'Food & Cooking',
    description: 'Готовка, рестораны, food blogger.',
    prompts: N('food-cooking', [
      { id: '01', label: 'Michelin Kitchen Pass', description: 'Chef pass, plating.',
        promptStyle: 'wearing a crisp white chef coat with rolled sleeves, at the pass of a michelin-style kitchen plating a dish, dramatic spotlight on the plate, professional-kitchen mood.' },
      { id: '02', label: 'Cozy Home Cook', description: 'Уютная домашняя кухня.',
        promptStyle: 'wearing a comfy linen apron over knit, in a warm wooden home kitchen with herbs on the windowsill, soft window daylight, friendly home-cook mood.' },
      { id: '03', label: 'Italian Trattoria', description: 'Италия, паста, ламповый свет.',
        promptStyle: 'wearing a white shirt with sleeves rolled, in a rustic italian trattoria with hanging garlic and warm string lights, mediterranean evening glow, joyful gastronomic mood.' },
      { id: '04', label: 'Food Stylist Studio', description: 'Food styling, мрамор.',
        promptStyle: 'wearing a clean linen apron, behind a marble food-styling counter with ingredients arranged top-down, bright north-facing window light, editorial food-stylist mood.', allowRigidPose: true },
      { id: '05', label: 'Street Food Night', description: 'Уличная еда, неон.',
        promptStyle: 'wearing a casual streetwear jacket, at a buzzing asian night-market food stall, neon signs glowing red and yellow behind, steamy atmosphere, street-food vlog mood.' },
      { id: '06', label: 'Farm-to-Table Garden', description: 'Сад, корзина овощей.',
        promptStyle: 'wearing a natural linen shirt with rolled sleeves and a garden apron, in a sunlit kitchen garden holding a basket of fresh produce, warm summer light, farm-to-table mood.' },
      { id: '07', label: 'Wine Cellar Sommelier', description: 'Sommelier, винный погреб.',
        promptStyle: 'wearing a refined dark vest over white shirt, in a stone wine cellar with bottles racked behind, warm candle-style ambient light, sommelier-expertise mood.' },
      { id: '08', label: 'Bakery Counter', description: 'Пекарня, мука, утренний свет.',
        promptStyle: 'wearing a flour-dusted apron over white tee, behind a wooden bakery counter with croissants and bread loaves, soft morning window light, artisan-bakery mood.' },
      { id: '09', label: 'BBQ Pit Master', description: 'Гриль, дым, мужской BBQ.',
        promptStyle: 'wearing a casual flannel with rolled sleeves, by a large outdoor BBQ smoker with rising smoke, warm sunset glow, pit-master mood.' },
      { id: '10', label: 'Cookbook Cover', description: 'Cookbook hero portrait.',
        promptStyle: 'wearing a clean neutral apron, against a soft warm-cream backdrop with a few key ingredients on a wooden board in front, golden afternoon light, cookbook-author portrait composition.', allowRigidPose: true },
    ]),
  },
  {
    slug: 'travel-lifestyle',
    label: 'Travel & Lifestyle',
    description: 'Путешествия, lifestyle-влоги.',
    prompts: N('travel-lifestyle', [
      { id: '01', label: 'Santorini Sunset', description: 'Санторини, белые арки.',
        promptStyle: 'wearing a flowing white linen outfit, on a santorini terrace with blue domes and white walls behind, warm aegean sunset light, dreamy travel-influencer mood.' },
      { id: '02', label: 'Tokyo Crossing', description: 'Сибуя, neon ночь.',
        promptStyle: 'wearing modern minimal travel outfit, at shibuya crossing at night with motion-blurred crowds and neon billboards, cinematic night-city mood.' },
      { id: '03', label: 'Bali Rice Fields', description: 'Бали, рисовые террасы.',
        promptStyle: 'wearing a natural linen co-ord, on a wooden swing overlooking lush bali rice terraces, soft tropical morning light, slow-travel mood.' },
      { id: '04', label: 'Alps Cabin', description: 'Альпы, snowy cabin.',
        promptStyle: 'wearing a chunky cream knit and beanie, on the porch of a snowy alpine wooden cabin, soft overcast snowy daylight, cozy travel-winter mood.' },
      { id: '05', label: 'Desert Dunes Vogue', description: 'Дюны, sahara editorial.',
        promptStyle: 'wearing flowing earth-tone desert attire, on golden sahara sand dunes at sunrise, dramatic long shadows and warm rim light, editorial desert-travel composition.' },
      { id: '06', label: 'Airport Lounge Premium', description: 'Lounge, золотое утро.',
        promptStyle: 'wearing a chic travel suit (cashmere, loafers) with a carry-on, in a premium airline lounge with floor-to-ceiling windows over the tarmac, warm morning light, business-class-traveler mood.' },
      { id: '07', label: 'Yacht Deck', description: 'Яхта, ривьера, лазурь.',
        promptStyle: 'wearing a relaxed white shirt and sunglasses, on the teak deck of a luxury yacht with azure mediterranean water behind, bright midday coastal light, yacht-life mood.' },
      { id: '08', label: 'Camper Van Vanlife', description: 'Vanlife, sunrise mountains.',
        promptStyle: 'wearing comfy outdoor layers, sitting in the open door of a converted camper van overlooking mountains at sunrise, warm golden first light, vanlife mood.' },
      { id: '09', label: 'Old Town Cafe', description: 'Кофейня, европейский квартал.',
        promptStyle: 'wearing a casual chic outfit (sweater and trousers), at an outdoor cafe in a charming old-town european square, soft overcast afternoon light, slow-travel cafe mood.' },
      { id: '10', label: 'Mountain Hike Summit', description: 'Гора, вершина, рюкзак.',
        promptStyle: 'wearing technical outdoor hiking gear and a backpack, at a mountain summit with epic ridge view behind, bright clear high-altitude daylight, adventure-travel mood.' },
    ]),
  },
  {
    slug: 'health-medicine',
    label: 'Health & Medicine',
    description: 'Врачи, доказательная медицина, здоровье.',
    prompts: N('health-medicine', [
      { id: '01', label: 'Doctor Clinic Portrait', description: 'Кабинет врача, белый халат.',
        promptStyle: 'wearing a crisp white medical coat with stethoscope, in a bright modern clinic office with neutral wood accents, soft cool clinical daylight, trustworthy doctor portrait.', allowRigidPose: true },
      { id: '02', label: 'Operating Room Calm', description: 'OR, синие хирургические тона.',
        promptStyle: 'wearing surgical scrubs and a surgical cap (no mask), in a clean operating-room setting with soft blue-green tones, cool clinical overhead light, calm surgeon mood.' },
      { id: '03', label: 'Research Lab', description: 'Лаборатория, наука.',
        promptStyle: 'wearing a white lab coat over neutral top, in a modern research lab with microscopes and clean glass equipment, bright neutral lab lighting, scientist mood.' },
      { id: '04', label: 'Pharmacy Counter', description: 'Аптека, чистый ритейл.',
        promptStyle: 'wearing a clean pharmacist coat, behind a modern pharmacy counter with neat shelves of products behind, bright clean retail lighting, friendly pharmacist mood.' },
      { id: '05', label: 'Dental Studio', description: 'Стоматолог, ярко-чистый офис.',
        promptStyle: 'wearing a fitted dental scrub top, in a bright modern dental office with chair in soft background blur, crisp clean daylight, confident dental-pro mood.' },
      { id: '06', label: 'Hospital Corridor', description: 'Больничный коридор, кинематика.',
        promptStyle: 'wearing scrubs with stethoscope around the neck, walking in a modern hospital corridor with motion-blurred figures, cinematic documentary feel, dedicated medic mood.' },
      { id: '07', label: 'Wellness Functional Med', description: 'Функциональная медицина, тепло.',
        promptStyle: 'wearing a soft cream knit cardigan over white shirt, in a warm wellness-clinic consultation room with plants and natural wood, soft warm window light, holistic-doctor mood.' },
      { id: '08', label: 'Patient Education', description: 'Объясняет схему, белая доска.',
        promptStyle: 'wearing a casual white coat over button-up, in front of a glass whiteboard with anatomical sketches, bright educational lighting, friendly educator-doctor mood.', allowRigidPose: true },
      { id: '09', label: 'Tech Surgeon', description: 'Tech surgeon AR, голограмма.',
        promptStyle: 'wearing modern surgical scrubs, in a futuristic surgical suite with faint holographic anatomical displays around, cool blue tech lighting, surgeon-of-the-future mood.' },
      { id: '10', label: 'Nutrition Coach Kitchen', description: 'Нутрициолог, кухня + еда.',
        promptStyle: 'wearing a clean modern casual outfit, in a bright kitchen consulting room with fresh produce on the counter, soft warm daylight, approachable nutrition-coach mood.' },
    ]),
  },
  {
    slug: 'parenting-family',
    label: 'Parenting & Family',
    description: 'Родительство, семейный контент.',
    prompts: N('parenting-family', [
      { id: '01', label: 'Sunny Family Kitchen', description: 'Семейная кухня, утро.',
        promptStyle: 'wearing a soft casual knit, in a bright family kitchen with cozy breakfast scene blurred behind, warm morning window light, happy parent mood.' },
      { id: '02', label: 'Reading Nook', description: 'Чтение детям, тёплый плед.',
        promptStyle: 'wearing a cozy cream sweater, sitting in a warm-lit reading nook with bookshelves and a chunky plaid throw, golden lamp glow, calm parent-storyteller mood.' },
      { id: '03', label: 'Mom Coach Studio', description: 'Mom-coach, ringlight, светлый фон.',
        promptStyle: 'wearing a soft pastel modern outfit, against a clean off-white wall with a leafy plant beside, soft ringlight, friendly mom-coach Reels composition.', allowRigidPose: true },
      { id: '04', label: 'Outdoor Family Picnic', description: 'Пикник, лето, газон.',
        promptStyle: 'wearing relaxed summer linen, on a sunlit lawn with a picnic blanket in soft background, warm golden afternoon light, family-summer mood.' },
      { id: '05', label: 'Bedtime Lamp', description: 'Сказка на ночь, мягкий свет.',
        promptStyle: 'wearing a soft loungewear knit, in a child-bedroom with twinkle string lights and storybook on a soft bed, warm dim ambient glow, tender parent mood.' },
      { id: '06', label: 'Stroller Park Walk', description: 'Парк, прогулка.',
        promptStyle: 'wearing casual chic outerwear, in a leafy park with a modern stroller (blurred), soft autumn daylight, real-life parent mood.' },
      { id: '07', label: 'Family Kitchen Cook', description: 'Готовит с ребёнком (only solo focus).',
        promptStyle: 'wearing a linen apron over casual top, in a warm modern kitchen with cooking ingredients on the counter, soft window daylight, friendly family-chef mood (single subject only in frame).' },
      { id: '08', label: 'Birthday Balloons', description: 'Праздник, шары.',
        promptStyle: 'wearing a fun bright casual outfit, in a soft-lit living room with pastel birthday balloons blurred behind, warm party glow, celebratory parent mood.' },
      { id: '09', label: 'Mom Brand Hero', description: 'Mom-brand, минимал бежевый.',
        promptStyle: 'wearing a chic beige minimal mom-uniform (linen + knit), against a soft cream studio backdrop, warm soft daylight, premium mom-brand composition.', allowRigidPose: true },
      { id: '10', label: 'Dad Workshop', description: 'Отец, мастерская.',
        promptStyle: 'wearing a casual flannel with rolled sleeves, in a warm wood home workshop with tools in soft background, golden side-window light, dad-craft mood.' },
    ]),
  },
  {
    slug: 'education-coaching',
    label: 'Education & Coaching',
    description: 'Преподаватели, эксперты, коучи.',
    prompts: N('education-coaching', [
      { id: '01', label: 'University Lecture Hall', description: 'Аудитория, профессор.',
        promptStyle: 'wearing a smart-casual jacket over button-up, in front of a wood-panelled university lecture hall, warm collegiate ambient light, professor-portrait mood.', allowRigidPose: true },
      { id: '02', label: 'Whiteboard Coach', description: 'Доска, маркер, объяснение.',
        promptStyle: 'wearing a casual blazer over tee, in front of a glass whiteboard with marker diagrams, bright clean classroom daylight, engaging coach mood.', allowRigidPose: true },
      { id: '03', label: 'Online Course Studio', description: 'Course-recording, ringlight.',
        promptStyle: 'wearing a modern smart-casual outfit, against a clean studio backdrop with brand-color accent panels, soft frontal ringlight catchlights, online-course host composition.', allowRigidPose: true },
      { id: '04', label: 'Library Scholar', description: 'Библиотека, deep work.',
        promptStyle: 'wearing a tweed jacket over knit, in a classical library with tall wooden shelves of books, warm tungsten reading light, scholar mood.' },
      { id: '05', label: 'Conference Stage', description: 'TEDx, сцена, спот.',
        promptStyle: 'wearing a refined casual blazer, on a tedx-style conference stage with a single warm spotlight and a clean red-circle backdrop, confident speaker pose.' },
      { id: '06', label: 'Workshop Studio', description: 'Workshop, аудитория.',
        promptStyle: 'wearing approachable smart-casual, in a workshop training room with chairs and a screen blurred behind, soft warm classroom light, facilitator mood.' },
      { id: '07', label: 'Coach Office', description: 'Кабинет коуча, плед, кресло.',
        promptStyle: 'wearing a soft knit cardigan over shirt, in a warm coaching office with a leather armchair and plants, soft warm tungsten ambient light, trusted-coach mood.' },
      { id: '08', label: 'YouTube Edutainment', description: 'YouTube edu studio.',
        promptStyle: 'wearing a colorful but tasteful modern outfit, on an edutainment-style youtube set with branded shelf props behind, bright clean studio lighting, engaging youtube-host composition.' },
      { id: '09', label: 'Book Author Portrait', description: 'Book-author portrait.',
        promptStyle: 'wearing a refined neutral outfit, in a warm home library with bookshelves behind, soft directional window light, author-portrait mood for a book cover.' },
      { id: '10', label: 'Outdoor Mentor Walk', description: 'Прогулка, ментор.',
        promptStyle: 'wearing a smart-casual outerwear layer, on a tree-lined path in soft autumn afternoon light, contemplative mentor mood.' },
    ]),
  },
  {
    slug: 'marketing-sales',
    label: 'Marketing & Sales',
    description: 'Маркетинг, продажи, performance.',
    prompts: N('marketing-sales', [
      { id: '01', label: 'Marketing War Room', description: 'War-room, метрики на стенах.',
        promptStyle: 'wearing a smart-casual blazer, in a modern marketing war room with dashboards on the wall showing growth charts, focused performance-marketer mood, cool ambient light.' },
      { id: '02', label: 'Brand Strategy Loft', description: 'Брендинг-студия, лофт.',
        promptStyle: 'wearing a tastefully minimal modern outfit, in a creative branding studio loft with mood boards behind, warm directional daylight, brand-strategist mood.' },
      { id: '03', label: 'Sales Call Headset', description: 'Sales bullpen, headset.',
        promptStyle: 'wearing a sharp business-casual shirt with a slim headset visible, in a modern sales floor with blurred colleagues at desks, bright clean office light, high-energy sales mood.' },
      { id: '04', label: 'Funnel Whiteboard', description: 'Whiteboard, sales funnel.',
        promptStyle: 'wearing a relaxed dark blazer, in front of a glass whiteboard with a clearly drawn sales funnel diagram, bright clean light, growth-marketer mood.', allowRigidPose: true },
      { id: '05', label: 'Performance Dashboard', description: 'Dashboard глядит в монитор.',
        promptStyle: 'wearing a modern dark tee under blazer, looking at a curved monitor showing colorful analytics dashboards, soft screen-glow on face, data-driven mood.' },
      { id: '06', label: 'Pitch Stage', description: 'Сцена, агентство, BIG headline.',
        promptStyle: 'wearing a confident dark casual blazer, on a small pitch stage with a big agency logo on the LED screen behind, dramatic spotlight, pitch-day energy.' },
      { id: '07', label: 'Modern Agency Office', description: 'Современное агентство, brand colors.',
        promptStyle: 'wearing a stylish smart-casual outfit, in a colorful modern marketing-agency office with brand accent walls and plants, bright daylight, creative-agency mood.' },
      { id: '08', label: 'Influencer Marketing Set', description: 'Influencer collab set.',
        promptStyle: 'wearing trendy casual streetwear, on a fun colorful influencer-style set with neon signage in the background, bright pop lighting, creator-marketing mood.' },
      { id: '09', label: 'Cold Calling Den', description: 'Закрытая комната, концентрация.',
        promptStyle: 'wearing a focused smart-casual outfit, in a quiet phone-room with single warm desk lamp and a notebook open, intense concentrated mood, deal-closer atmosphere.' },
      { id: '10', label: 'Marketing Conference', description: 'Конференция, badge.',
        promptStyle: 'wearing a smart-casual blazer with a small conference lanyard, in a marketing conference foyer with banners and motion-blurred attendees, warm event lighting, networking mood.' },
    ]),
  },
  {
    slug: 'entrepreneurship-startup',
    label: 'Entrepreneurship & Startup',
    description: 'Предпринимательство, founders.',
    prompts: N('entrepreneurship-startup', [
      { id: '01', label: 'Founder Garage', description: 'Гараж, начинаем стартап.',
        promptStyle: 'wearing a worn-in tee and jeans, in a converted garage workspace with raw concrete walls and a single workbench, warm garage-lamp glow, scrappy-founder mood.' },
      { id: '02', label: 'Coffee Shop Founder', description: 'Coffee-shop ноутбук.',
        promptStyle: 'wearing a smart casual layer (knit + jacket), at a wooden coffee-shop table with macbook and espresso cup, soft warm window light, indie-founder mood.' },
      { id: '03', label: 'Series-A Pitch', description: 'Pitch zoom, доска.',
        promptStyle: 'wearing a sharp casual blazer over tee, in a clean modern boardroom with a presentation projected behind, cool professional daylight, series-a founder mood.' },
      { id: '04', label: 'Bootstrap Loft', description: 'Маленькая команда, лофт.',
        promptStyle: 'wearing a casual hoodie under blazer, in a small startup loft with whiteboards on the walls and team activity blurred behind, bright modern daylight, bootstrap-founder mood.' },
      { id: '05', label: 'Magazine Founder Portrait', description: 'Forbes-style portrait.',
        promptStyle: 'wearing a tailored navy suit (no tie), against a moody deep-blue editorial backdrop, dramatic single key light, forbes-style founder portrait composition.', allowRigidPose: true },
      { id: '06', label: 'Demo Day LED', description: 'Demo-day LED stage.',
        promptStyle: 'wearing a clean modern dark outfit, on a demo-day stage with a giant LED slide of your product behind, sharp spotlight, confident-pitch mood.' },
      { id: '07', label: 'Hustle Mode Late Night', description: 'Поздний офис, ноутбук, кофе.',
        promptStyle: 'wearing a relaxed hoodie, at a desk late at night with laptop glow and a coffee cup, dim ambient warm light, late-night hustle mood.' },
      { id: '08', label: 'Cap Table Strategy', description: 'White-board cap table.',
        promptStyle: 'wearing a casual blazer over tee, in front of a glass whiteboard with cap-table sketches and arrows, bright clean light, strategic-founder mood.', allowRigidPose: true },
      { id: '09', label: 'Co-Founder Dyad Hero', description: 'Founder hero, alone but cinematic.',
        promptStyle: 'wearing a confident dark jacket, in a modern startup office with motion-blurred team behind, warm cinematic ambient light, leadership composition (single subject in focus).' },
      { id: '10', label: 'Cover Wallstreet Style', description: 'Founder Wall-street-style.',
        promptStyle: 'wearing a refined dark suit, against a deep-amber editorial backdrop, dramatic chiaroscuro lighting, premium founder magazine-cover composition.', allowRigidPose: true },
    ]),
  },
  {
    slug: 'personal-branding',
    label: 'Personal Branding & Mindset',
    description: 'Личный бренд, продуктивность, мотивация.',
    prompts: N('personal-branding', [
      { id: '01', label: 'Modern Hero Portrait', description: 'Premium hero portrait.',
        promptStyle: 'wearing a sharp modern minimal outfit, against a deep slate-grey seamless backdrop with subtle gradient, dramatic editorial key light, premium personal-brand hero composition.', allowRigidPose: true },
      { id: '02', label: 'Confidence Editorial', description: 'Уверенность, цвет акцент.',
        promptStyle: 'wearing a tailored confident outfit in a single accent color, against a contrasting clean studio backdrop, sharp editorial lighting, confident editorial portrait composition.', allowRigidPose: true },
      { id: '03', label: 'Mindset Morning Light', description: 'Утро, окно, кофе.',
        promptStyle: 'wearing a soft modern knit, by a large window with morning light streaming in and a mug in hand, calm reflective mood, mindset-content composition.' },
      { id: '04', label: 'Reels Talking Head', description: 'Reels talking head set.',
        promptStyle: 'wearing a clean modern outfit with one brand-accent element, against a tasteful textured wall with one plant on the side, soft frontal ringlight, talking-head Reels composition.', allowRigidPose: true },
      { id: '05', label: 'Notebook Strategy', description: 'Notebook + ручка, deep work.',
        promptStyle: 'wearing a focused smart-casual outfit, at a wooden desk with an open leather notebook and a fountain pen, warm desk-lamp glow, intentional thinker mood.' },
      { id: '06', label: 'Power Stance Hero', description: 'Power-stance, негативное пространство.',
        promptStyle: 'wearing a strong silhouette outfit (long coat or structured jacket), in a wide architectural space with strong leading lines, cinematic side-light, power-stance composition with negative space.' },
      { id: '07', label: 'Lifestyle Walk', description: 'Walking shot, city.',
        promptStyle: 'wearing a refined casual coat over neutral basics, walking on a sunlit city street with shallow depth of field, golden hour rim light, lifestyle-vlog mood.' },
      { id: '08', label: 'Quote Card Cover', description: 'Cover для цитаты, негативное пространство.',
        promptStyle: 'wearing a clean minimal outfit, against a deep monochrome studio backdrop, dramatic chiaroscuro key light, composition with significant negative space on one side for a quote overlay.', allowRigidPose: true },
      { id: '09', label: 'Mentor Library', description: 'Библиотека, ментор.',
        promptStyle: 'wearing a refined knit cardigan over button-up, in a warm wood library with books behind, soft tungsten reading light, mentor-portrait mood.' },
      { id: '10', label: 'Brand Color Pop', description: 'Brand-color hero, цвет фоном.',
        promptStyle: 'wearing a tasteful neutral outfit, against a flat saturated brand-color backdrop (single bold color), even soft studio light, branded hero portrait composition.', allowRigidPose: true },
    ]),
  },
  {
    slug: 'music-entertainment',
    label: 'Music & Entertainment',
    description: 'Музыканты, артисты, шоубиз.',
    prompts: N('music-entertainment', [
      { id: '01', label: 'Stage Spotlight', description: 'Stage, mic, спотлайт.',
        promptStyle: 'wearing a bold stage outfit, on a dark concert stage with a single dramatic spotlight and a vintage microphone, smoky atmosphere, performance moment mood.' },
      { id: '02', label: 'Recording Studio', description: 'Recording booth, попфильтр.',
        promptStyle: 'wearing a cool casual outfit, behind a pop-filter and studio microphone in a recording booth, warm ambient studio glow, recording-session mood.' },
      { id: '03', label: 'DJ Booth Neon', description: 'DJ booth, club, neon.',
        promptStyle: 'wearing a streetwear bomber and headphones around the neck, at a high-end DJ booth with neon club lighting behind in magenta and cyan, dynamic nightclub mood.' },
      { id: '04', label: 'Acoustic Living Room', description: 'Гитара, гостиная.',
        promptStyle: 'wearing a relaxed casual outfit with an acoustic guitar visible, in a warm cozy living room with soft string-lights, warm tungsten ambient glow, intimate acoustic mood.' },
      { id: '05', label: 'Magazine Cover Artist', description: 'Rolling Stone style cover.',
        promptStyle: 'wearing a bold artist-style outfit, against a moody graphic editorial backdrop, dramatic single key light, rolling-stone-cover composition.', allowRigidPose: true },
      { id: '06', label: 'Backstage Greenroom', description: 'Бэкстейдж, отражение.',
        promptStyle: 'wearing a confident stage-ready outfit, in a backstage greenroom with a vanity mirror surrounded by bulbs, warm flattering glow, pre-show moment mood.' },
      { id: '07', label: 'Rooftop Music Video', description: 'Rooftop, sunset video shoot.',
        promptStyle: 'wearing an iconic music-video outfit, on an urban rooftop at sunset with city skyline behind, warm cinematic golden light, music-video-still mood.' },
      { id: '08', label: 'Hip-Hop Alley', description: 'Альюй, хип-хоп.',
        promptStyle: 'wearing classic streetwear (oversized hoodie, chains), in a dark urban alleyway with graffiti walls, dramatic single overhead light, hip-hop editorial mood.' },
      { id: '09', label: 'Festival Crowd', description: 'Фестиваль, толпа в bokeh.',
        promptStyle: 'wearing a festival-stage outfit, in front of a motion-blurred crowd with stage haze and beams of colored light, dynamic live-festival mood.' },
      { id: '10', label: 'Album Cover Studio', description: 'Album cover hero portrait.',
        promptStyle: 'wearing an artist-defining outfit, against a richly textured colored backdrop, dramatic mood lighting with one strong color cast, album-cover hero composition.', allowRigidPose: true },
    ]),
  },
  {
    slug: 'gaming-streaming',
    label: 'Gaming & Streaming',
    description: 'Геймеры, стримеры, киберспорт.',
    prompts: N('gaming-streaming', [
      { id: '01', label: 'Streamer Setup RGB', description: 'Стримерская комната, RGB.',
        promptStyle: 'wearing a casual gaming hoodie, in a dark gamer room with RGB-lit wall panels, mechanical keyboard glow, gaming-streamer atmospheric mood.' },
      { id: '02', label: 'Twitch Webcam Hero', description: 'Webcam hero, ringlight.',
        promptStyle: 'wearing a streamer-branded hoodie, against a colorful streamer-room background with neon accents, soft frontal ringlight catchlights, webcam-ready streamer composition.', allowRigidPose: true },
      { id: '03', label: 'Esports Pro Jersey', description: 'Esports jersey, team logo neutral.',
        promptStyle: 'wearing a sleek modern esports jersey, in a pro-gaming team training room with PC stations blurred behind, cool cyan accent lighting, esports-pro mood.' },
      { id: '04', label: 'Cyberpunk Console', description: 'Console gamer cyberpunk.',
        promptStyle: 'wearing a futurist streetwear jacket, in a cyberpunk-styled living room with neon signs and a giant TV running a colorful game, magenta-cyan glow, console-gamer mood.' },
      { id: '05', label: 'LAN Party Atmosphere', description: 'LAN party night.',
        promptStyle: 'wearing a casual gamer tee, in a LAN-party space with rows of PCs and blurred players, intense screen-glow on the face, lan-event mood.' },
      { id: '06', label: 'Speedrunner Den', description: 'Speedrunner, single rig.',
        promptStyle: 'wearing a focused casual hoodie, at a clean single-monitor gaming setup with a stopwatch on screen, intense focused mood, speedrun atmosphere.' },
      { id: '07', label: 'Cosplay Editorial', description: 'Cosplay-inspired light.',
        promptStyle: 'wearing a creative cosplay-inspired modern outfit (no specific IP), with dramatic colored gels (purple+teal) and atmospheric haze, cinematic gamer-fantasy mood.' },
      { id: '08', label: 'Mobile Gamer Cafe', description: 'Mobile gamer, кафе, неон.',
        promptStyle: 'wearing modern streetwear, in a neon-lit gaming cafe with screens around, motion-blurred players in the back, mobile-esports atmospheric mood.' },
      { id: '09', label: 'YouTube Gaming Set', description: 'YouTube gaming set, branded.',
        promptStyle: 'wearing a clean branded hoodie, against a youtube-gaming creator backdrop with shelf of collectibles, bright clean studio light with rgb accent, youtube-host composition.', allowRigidPose: true },
      { id: '10', label: 'Arena Stage Esports', description: 'Esports arena stage.',
        promptStyle: 'wearing a sleek esports jersey, on a massive esports arena stage with crowd silhouettes and giant LED screens behind, dynamic stadium spotlights, championship moment mood.' },
    ]),
  },
  {
    slug: 'photography-creative',
    label: 'Photography & Creative',
    description: 'Фотографы, креаторы, режиссёры.',
    prompts: N('photography-creative', [
      { id: '01', label: 'Photo Studio Hero', description: 'Studio with softbox.',
        promptStyle: 'wearing a relaxed dark creative outfit with a camera around the neck, in a pro photo studio with softboxes visible, warm directional key light, photographer-portrait mood.' },
      { id: '02', label: 'Field Photographer', description: 'Поле, leica, плёнка.',
        promptStyle: 'wearing rugged stylish outerwear, in a wide natural landscape holding a leica-style camera, golden-hour warm rim light, travel-photographer mood.' },
      { id: '03', label: 'Darkroom Mood', description: 'Darkroom, красный свет.',
        promptStyle: 'wearing a casual artist outfit, in a darkroom with red safelight glow and hanging photo prints, atmospheric analog mood.' },
      { id: '04', label: 'Filmmaker On-Set', description: 'On-set, director chair.',
        promptStyle: 'wearing a director-style layered casual outfit, on a film-set with cinema camera and crew blurred behind, warm cinematic ambient light, on-set director mood.' },
      { id: '05', label: 'Creative Studio Loft', description: 'Студия, краски, мудборд.',
        promptStyle: 'wearing relaxed creative-casual layers, in a creative studio loft with mood boards and paint swatches on the wall, warm natural daylight, creative-director mood.' },
      { id: '06', label: 'Editorial B&W', description: 'Чёрно-белый portrait.',
        promptStyle: 'wearing a sleek minimal outfit, in a black-and-white editorial style with dramatic key light and deep shadows, fine-art photography portrait composition.', allowRigidPose: true },
      { id: '07', label: 'Street Photographer', description: 'Tokyo street photog.',
        promptStyle: 'wearing a worn-in jacket with a camera bag, on a busy tokyo street at dusk with neon reflections, cinematic street-photographer mood.' },
      { id: '08', label: 'Designer Studio Mac', description: 'Designer studio, mac.',
        promptStyle: 'wearing minimal creative-casual, at a clean designer workstation with iMac and color swatches, soft daylight, designer-creative mood.' },
      { id: '09', label: 'Gallery Show', description: 'Галерея, белые стены.',
        promptStyle: 'wearing an artistic minimal outfit, in a contemporary art gallery with white walls and large prints behind, soft museum-style lighting, artist-portrait mood.' },
      { id: '10', label: 'Behind the Camera POV', description: 'Behind camera (mostly subject).',
        promptStyle: 'wearing a relaxed creative outfit, partially behind a large cinema camera with viewfinder visible, dramatic on-set lighting, cinematographer mood (subject clearly in frame, not obscured by gear).' },
    ]),
  },
  {
    slug: 'cars-auto',
    label: 'Cars & Auto',
    description: 'Автомобили, тюнинг, supercars.',
    prompts: N('cars-auto', [
      { id: '01', label: 'Supercar Garage', description: 'Гараж, supercar, sodium.',
        promptStyle: 'wearing a sleek modern jacket, in a private supercar garage with a blurred matte-black supercar behind, warm sodium accent lights and cool ambient fill, gearhead luxury mood.' },
      { id: '02', label: 'Track Day Pit', description: 'Pit lane, helmet.',
        promptStyle: 'wearing a clean modern racing-inspired jacket holding a racing helmet, in a track pit lane with race-team activity blurred behind, bright track daylight, race-day mood.' },
      { id: '03', label: 'Showroom Glass', description: 'Премиальный шоурум.',
        promptStyle: 'wearing a refined business-casual outfit, in a premium car showroom with glossy floors and a blurred luxury car behind, clean architectural lighting, dealership-pro mood.' },
      { id: '04', label: 'JDM Night Tokyo', description: 'JDM Tokyo, neon.',
        promptStyle: 'wearing a stylish bomber jacket, on a tokyo night street with a tuned car blurred behind, neon signs glowing pink and cyan, jdm-culture cinematic mood.' },
      { id: '05', label: 'Off-Road Adventure', description: 'Off-road, mud, jeep.',
        promptStyle: 'wearing rugged outdoor layers, next to a mud-spattered off-road vehicle blurred in the background, dramatic mountain landscape and golden light, adventure-overland mood.' },
      { id: '06', label: 'Restomod Workshop', description: 'Реставрация, винтаж.',
        promptStyle: 'wearing a worn-in mechanic-style jacket, in a restomod workshop with vintage parts on a wooden bench, warm workshop lamp light, craftsman mood.' },
      { id: '07', label: 'Highway Sunset', description: 'Открытое шоссе на закате.',
        promptStyle: 'wearing a stylish driving jacket and aviators, on the side of an open desert highway at sunset, warm cinematic golden light, road-trip mood.' },
      { id: '08', label: 'Detailer Studio', description: 'Detailing, glossy paint.',
        promptStyle: 'wearing a casual detailer polo with a microfiber cloth, in a detailing studio with glossy reflective car body in soft background, controlled even spotlights, car-detailing mood.' },
      { id: '09', label: 'F1 Paddock', description: 'F1 paddock pass.',
        promptStyle: 'wearing a modern motorsport-inspired jacket with a paddock pass, in a motorsport paddock with team garage activity blurred behind, bright race-weekend daylight, paddock-insider mood.' },
      { id: '10', label: 'Magazine Cover Auto', description: 'Auto-magazine hero.',
        promptStyle: 'wearing a stylish driving outfit, against a deep moody studio backdrop with a blurred luxury car silhouette, dramatic single key light, auto-magazine cover composition.', allowRigidPose: true },
    ]),
  },
  {
    slug: 'crypto-web3',
    label: 'Crypto & Web3',
    description: 'Крипта, Web3, DeFi, NFT.',
    prompts: N('crypto-web3', [
      { id: '01', label: 'Crypto Trader Den', description: 'Trader, green candles.',
        promptStyle: 'wearing a sleek dark hoodie under a blazer, at a multi-monitor desk with neon-green crypto candlestick charts glowing, dim room with screen-cast light on face, crypto-trader mood.' },
      { id: '02', label: 'Web3 Conference Stage', description: 'Web3 conference stage.',
        promptStyle: 'wearing a modern smart-casual outfit, on a web3 conference stage with a glowing logo on the LED screen behind, sharp keynote spotlight, web3-speaker mood.' },
      { id: '03', label: 'NFT Studio Neon', description: 'NFT art studio, magenta.',
        promptStyle: 'wearing a futurist streetwear jacket, in a neon-lit creative studio with NFT-style abstract art on screens behind, magenta-cyan ambient glow, NFT-artist mood.' },
      { id: '04', label: 'DAO Coworking', description: 'Dao remote co-work.',
        promptStyle: 'wearing modern casual layers, in a minimalist coworking space with multiple laptops on the table and a discord-style screen visible, cool clean daylight, dao-contributor mood.' },
      { id: '05', label: 'Bitcoin Maximalist', description: 'BTC orange editorial.',
        promptStyle: 'wearing a confident dark casual outfit, against a deep-orange editorial backdrop with subtle bitcoin-orange rim light, premium editorial composition.', allowRigidPose: true },
      { id: '06', label: 'Ethereum Cyber Lab', description: 'ETH purple cyber lab.',
        promptStyle: 'wearing a futurist tech jacket, in a dark lab with purple-blue accent lighting and faint blockchain-graph projections behind, sci-fi web3 mood.' },
      { id: '07', label: 'Crypto Podcast Studio', description: 'Crypto podcast warm.',
        promptStyle: 'wearing a stylish modern casual outfit, in a warm crypto-podcast studio with a large mic and amber accent lighting, crypto-content mood.' },
      { id: '08', label: 'Trading Floor Night', description: 'Stock-trading floor night.',
        promptStyle: 'wearing a refined dark blazer, in a futurist trading-floor environment at night with ticker LEDs scrolling around, cinematic dramatic lighting, night-trader mood.' },
      { id: '09', label: 'Web3 Founder Hero', description: 'Web3 founder hero portrait.',
        promptStyle: 'wearing a clean modern dark outfit, against a deep navy backdrop with subtle holographic accents, dramatic single key light, web3 founder portrait composition.', allowRigidPose: true },
      { id: '10', label: 'Metaverse Avatar Set', description: 'Метавселенная, синтетика.',
        promptStyle: 'wearing a modern metaverse-inspired streetwear, in a synthetic-feeling environment with soft pastel gradients and floating geometric shapes, futurist metaverse mood.' },
    ]),
  },
  {
    slug: 'spirituality-selfhelp',
    label: 'Spirituality & Self-help',
    description: 'Психология, духовность, mindfulness.',
    prompts: N('spirituality-selfhelp', [
      { id: '01', label: 'Meditation Sunrise', description: 'Медитация, рассвет.',
        promptStyle: 'wearing flowing natural linen, in a calm rooftop setting at sunrise with soft coral light, gentle mindful composition, meditation mood.' },
      { id: '02', label: 'Therapy Office', description: 'Кабинет психолога, тепло.',
        promptStyle: 'wearing a warm knit cardigan over neutral shirt, in a cozy therapist office with a soft armchair and plants, warm tungsten ambient light, trusted-therapist mood.' },
      { id: '03', label: 'Zen Garden Robe', description: 'Zen garden, льняной халат.',
        promptStyle: 'wearing a flowing earth-tone linen robe, in a japanese zen garden with raked sand and stones, soft overcast daylight, calm spiritual mood.' },
      { id: '04', label: 'Yoga Studio Hero', description: 'Студия йоги, mat.',
        promptStyle: 'wearing a serene neutral yoga set, in a minimalist sunlit yoga studio with wooden floor and plants, soft warm window daylight, gentle yogi mood.' },
      { id: '05', label: 'Crystal Healing Room', description: 'Crystal room, ароматерапия.',
        promptStyle: 'wearing flowing pastel layers, in a soft pastel healing room with crystals, candles, and incense smoke, warm gentle ambient glow, energy-worker mood.' },
      { id: '06', label: 'Forest Bath', description: 'Лесная купель.',
        promptStyle: 'wearing natural earth-tone outerwear, on a misty forest path with shafts of sunlight through trees, cool calm green-tinted light, forest-bathing mood.' },
      { id: '07', label: 'Mindset Coach Studio', description: 'Mindset coach, ringlight.',
        promptStyle: 'wearing a soft pastel knit, against a clean off-white studio with one large plant beside, soft ringlight, mindset-coach Reels composition.', allowRigidPose: true },
      { id: '08', label: 'Sound Healing', description: 'Поющие чаши, mood.',
        promptStyle: 'wearing a flowing pastel robe, in a candlelit room with singing bowls in front, warm flickering ambient candlelight, sound-healer mood.' },
      { id: '09', label: 'Spiritual Author Portrait', description: 'Author portrait, warm shelf.',
        promptStyle: 'wearing a warm linen outfit, in a sunlit room with a bookshelf of spiritual books behind, warm afternoon window light, spiritual-author portrait mood.' },
      { id: '10', label: 'Ocean Sunset Stillness', description: 'Океан, закат, штиль.',
        promptStyle: 'wearing a flowing white linen outfit, on a quiet beach at sunset with calm reflective water, warm coral horizon light, deep-stillness mood.' },
    ]),
  },
];

export function nicheBySlug(slug: string): Niche | null {
  return NICHES.find((n) => n.slug === slug) ?? null;
}

export function nichePromptBySlug(nicheSlug: string, promptSlug: string): NichePrompt | null {
  const niche = nicheBySlug(nicheSlug);
  if (!niche) return null;
  return niche.prompts.find((p) => p.slug === promptSlug) ?? null;
}
